language: go
go: "1.12"
env:
  global:
    - secure: "XFxZ/Lribl3fTo6NtiFH5VTQuHKRRz5N4FhGY6+k6KvYivEuOMs9frjLZ/r5fMGs5uzgi7pNLuZ0kL8+gVwmaIE/MadMtPZxsUF94cY1FwApsymbpBCgy5J/ROfbV210uD37GUay/AeHqRIm4b80tareiENfzDumJQqLdkpFtpXvSihkt4TSSz71Usg9nLu//upEUOEyWBFQLAFIr+wA9Xps2KwsnsWaWVDAmwG4nBHEuKKRYgZx7XCrJUMvscA0AoMpBh9USRtLcivgTeDBKiK7EMM5IzjVIKYGZAzqoORfI5AV/aMZv8Rm0Yd9xzI4UgpUYrqRNtDF5YbslejjQx5ysaYLFZ0zotw8C35Huk0q4t0LzxdVLjdj3TXU8AV7qpl7CHPayDm8Pk5NHzofSoKDwMFjFgFsN5YWK7Ga8KDCN9/RjWInLhiBzMdatoGxfcXtEfKy5Q/sZvGULxVOreKs2HxRNa0Lmau6tdZgwIv7WiMUok9CzpK6fUqIoK7eQQRX8VPLGRIcOC41pHqP2fkk3zjDn2Z525SFyoWHDu79mcMYLH2QHf2WkmT2STEquVu7QojwVf/MjmbC1W2V/SSbA/cVrXnmzef3tv99qkn6NvVtBxQQEAScdnGtkSX7CQ+8pVWdDIlDWkOqoUU7zjpB8VR9zB42D+D47Czwsjg="
    - secure: "d9Oymc/CdidkWX+vjCKj9p0jB6YVsFNgc5JJDgWXzReO3nx5WjnL9ZGnIw30H3zWE4TTzSuTHYGUA0gE9yRbdZshaenUVIX+DIryYhKqJsUDAbAN53NF++h41sEXOrGt/2gu9aBDfULwhrJ0Gcge+CYEnV8zPI4yhIvIhf3qMKh42oHDPd0TuencUq2ugn0fhJsIQGEBGLd06qGgBdMoHXWZu/M75Px/Qo835x7DbLH6NS+UvNUKvHf+GSH45En5myrH45LnP+yovsz65Z/P8tRlGV8QicQwL3Wy1E1xleSrqxvzMistU/g4ADUn5VsYJjmjbxHJ3f6r3MWjjBZ0VZFut3utKrKkz8I1j2T2WCeNtcnbgULZt/XlQOY2ugm6LFCB2AZD/XMIZGljqdGxZ2xVgoxjy8s9qPMNJmyxkZUbCrLqZtLkAoHmaIbQWUQ3hWr+27arZ50WJYut/bgMxCry8PQjIJ0KbQ6TNkdT+Eyaw581OO0QOPKMStGYDgXFVPjus7ymCf9ElMHcvDG+4XkJIi18hcQ+c8cASrfF3TcVtrFbdsygIHdwGd/XxO8SX1mxWeZnSJfvbVBUAGZN3WScHVYe74dlgqFPv5gRG/fI1IiSapFelCEEyynZh0AIDTDCCgZxLPdtOFQnFSkItSOepcdgviUkrDiDjHQwUj8="
    - GO111MODULE=on
services:
  - docker
go_import_path: github.com/trinchan/saiki
script: make ci

deploy:
  provider: script
  script: bash ./hack/push_image.sh
  on:
    branch: master
    tags: true